### PR TITLE
Fix makeAppx to support spaces in path arguments

### PR DESCRIPTION
**Pull request by rnrneverdies**
Fixes https://github.com/MicrosoftEdge/CloudAppX/issues/4

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @rnrneverdies!

Would you mind rebasing without the package version bump?

**Comment by rnrneverdies** [comment]
@jdalton done!

**Comment by boyofgreen** [comment]
Hi JDD, Did you take a look at this, can we move it forward?

**Comment by rnrneverdies** [comment]
Closing this due to inactivity. Feel free to reopen it.

**Pull request closed without merging**
